version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"  # Assure-toi que tu accèdes sur le bon port
    volumes:
      - ./Serie3/activite1:/usr/share/nginx/html  # Chemin correct vers ton dossier
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./Serie3/activite1:/code

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  dbdata:
